---
  extends: 
  - eslint:recommended
  - google
  env:
    es6: true
    node: true
    browser: false
  parserOptions: 
    ecmaVersion: 10
    sourceType: module
  rules:
    semi: 
      - 1
      - never
    object-curly-spacing:
      - 2
      - always
    indent:
      - error
      - 2
    max-len:
      - error
      - 120
