name: heimdall-ledstring
base: core18
version: '0.1+git'
summary: Leverages AWS IoT to receive colors for an LED strip
description: |
  AWS IoT is used to transmit arrays of colors to transfer to an LED string.
  This relies on AWS IoT certificates, ensure they are placed in the ~/.iot_certs directory
  You will need to run `snap connect heimdall-ledstring:ledstring-certs` to allow this snap to use your certificates.
  
  Input variables available are as follows ~

    HOST_URL          (REQUIRED) - This is your Host URL from AWS IoT
    CERTIFICATE_ID    (REQUIRED) - This is the prefix to the cert files you receive from AWS IoT
    CERTIFICATE_PATH  (OPTIONAL) - Defaults to ~/.iot_certs
    CLIENT_ID         (OPTIONAL) - Defaults to LEDController
    CA_FILE_NAME      (OPTIONAL) - Defaults to AmazonRootCA1.pem

  You will need the following files ~
    certificate.pem.crt
    private.pem.key
    AmazonRootCA1.pem

architectures:
  - amd64
  - arm64
  - armhf

hooks:
  install:
      plugs: 
        - network

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  client:
    plugin: nodejs
    nodejs-version: '12.10.0'
    nodejs-package-manager: npm
    source: .
  
apps:
  heimdall-ledstring:
    plugs:
      - ledstring-certs
      - network
    environment:
      OPTS_JSON: $SNAP_USER_DATA/options/config.json
    daemon: simple
    command: heimdall-ledstring
